# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr6', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='pages_num',
            field=models.IntegerField(default=0),
        ),
    ]
