# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr6', '0002_bookmodel_pages_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('books_num', models.IntegerField(default=0)),
                ('book', models.ManyToManyField(to='lr6.BookModel')),
            ],
        ),
    ]
