# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.IntegerField(unique=True)),
                ('room', models.IntegerField(max_length=4)),
                ('datein', models.DateField()),
                ('dateout', models.DateField()),
                ('user', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rate', models.IntegerField(default='0')),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('photopath', models.URLField()),
                ('services', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, unique=True)),
                ('hotel', models.CharField(max_length=255, unique=True)),
                ('datein', models.DateField()),
                ('dateout', models.DateField()),
                ('review', models.TextField()),
                ('mark', models.FloatField()),
                ('photopath', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=4, unique=True)),
                ('hotelname', models.CharField(max_length=511)),
                ('description', models.TextField(max_length=2000)),
                ('photopath', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(default='M', max_length=1)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
